baseURL = ""
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Kritika Poddar"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright Â© KritikaPoddar 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/xbjqnokq"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo9.png"

[params.address]
address = "T7, Sri Durga Palmgrove, 4 th Cross, 80ft Road, Kormangala, Bengaluru-560095"
email = "kritikapoddar3@example.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(91) 8159819690"

[params.map]
APIkey = "AIzaSyCUuuOnLZogxCAlqV1ZgclUUYvoi5RqclY"
latitude = "12.9364123"
longitude = "77.6263515"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/kritikapoddar/"
weight = 1
[[params.social]]
icon = "fa fa-instagram"
url = "https://www.instagram.com/_kritikapoddar/"
weight = 2
